keycloak:
  replicaCount: 1
  image:
    repository: jboss/keycloak
    pullPolicy: Always
    tag: 7.0.0

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  serviceAccount:
    create: true
    annotations: 
    name:  
  service:
    annotations: 
      kubernetes.io/ingress.class: alb
    labels: {}
    type: LoadBalancer
    port: 80
  PodAnnotations: 
#       kubernetes.io/ingress.class: alb
  username: "admin"
  password: "admin"
  proxyAddressForwarding: "true"
  persistence:   
    deployPostgres: false
  podSecurityContext: {}
  securityContext: {} 
  ingress:
    enabled: false
    annotations: {}
    hosts:
      - host: chart-example.local 
        paths: []

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80

  nodeSelector: {}

  tolerations: []
