apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: dev
  labels:
    name: keycloak
spec:
  type: {{ .Values.keycloak.service.type }}
  ports:
    - port: {{ .Values.keycloak.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    name: keycloak
